In [1]:
import torch
print(torch.__version__)

2.8.0+cu126


# 1) Creating Tensors

In [2]:
# Using empty

a = torch.empty(2, 3)                   # .empty(shape) returns a tensor without initializing its values- means it will give random garbage values that were already
print(a)                                # exisiting in allocated memory block

tensor([[1.4580e-19, 1.8179e+31, 1.8524e+28],
        [2.1715e-18, 1.6968e-07, 2.6833e-09]])


In [3]:
type(a)

torch.Tensor

In [4]:
# Using zeros

torch.zeros(2, 3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [5]:
# Using ones

torch.ones(3, 2)

tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])

In [6]:
# Using rand

print(torch.rand(2, 2))         # .rand(shape) gives random values in the tensor of given size
print(torch.rand(2, 2))

tensor([[0.9432, 0.4734],
        [0.1272, 0.5074]])
tensor([[0.2726, 0.3392],
        [0.6050, 0.5955]])


In [7]:
# Reproducing same random values using seed

torch.manual_seed(13)

print(torch.rand(2, 2))

print(torch.rand(2, 2))

torch.manual_seed(13)            # Whenever we want .rand(shape) to produce same random values we have to write .manual_seed() again (With the specified numaber, here 13)
print(torch.rand(2, 2))

tensor([[0.0918, 0.4794],
        [0.8106, 0.0151]])
tensor([[0.0153, 0.6036],
        [0.2318, 0.8633]])
tensor([[0.0918, 0.4794],
        [0.8106, 0.0151]])


In [8]:
# Using tensor

torch.tensor([[1,2,3],[4,5,6]])     # .tensor() gives custom tensors by user

tensor([[1, 2, 3],
        [4, 5, 6]])

In [9]:
# Using .randint()

torch.randint(size = (2,3), low = 0, high = 10)            # creates a tensor filled with random integers between [low, high).

tensor([[8, 6, 6],
        [9, 4, 8]])

In [10]:
# other ways

# arange
print("using arange ->", torch.arange(0,10,2))

# using linspace
print("using linspace ->", torch.linspace(0,10,10))

# using eye
print("using eye ->", torch.eye(5))

# using full
print("using full ->", torch.full((3, 3), 5))

using arange -> tensor([0, 2, 4, 6, 8])
using linspace -> tensor([ 0.0000,  1.1111,  2.2222,  3.3333,  4.4444,  5.5556,  6.6667,  7.7778,
         8.8889, 10.0000])
using eye -> tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])
using full -> tensor([[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]])


# 2) Tensor properties

### 2.1) Tensor data-types

In [11]:
# Finding data type of a tensor

a.dtype

torch.float32

In [12]:
# Assigning the data type, while creating a tensor

torch.tensor([[1,2], [5,6]], dtype = torch.float64)

tensor([[1., 2.],
        [5., 6.]], dtype=torch.float64)

In [13]:
# Changing data type of an existing tensor

a.to(torch.int32)

tensor([[          0, -2147483648, -2147483648],
        [          0,           0,           0]], dtype=torch.int32)

#### Different types of **Data Types** available for tensors:

| **Data Type**             | **Dtype**         | **Description**                                                                                                                                                                |
|---------------------------|-------------------|--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| **32-bit Floating Point** | `torch.float32`   | Standard floating-point type used for most deep learning tasks. Provides a balance between precision and memory usage.                                                         |
| **64-bit Floating Point** | `torch.float64`   | Double-precision floating point. Useful for high-precision numerical tasks but uses more memory.                                                                               |
| **16-bit Floating Point** | `torch.float16`   | Half-precision floating point. Commonly used in mixed-precision training to reduce memory and computational overhead on modern GPUs.                                            |
| **BFloat16**              | `torch.bfloat16`  | Brain floating-point format with reduced precision compared to `float16`. Used in mixed-precision training, especially on TPUs.                                                |
| **8-bit Floating Point**  | `torch.float8`    | Ultra-low-precision floating point. Used for experimental applications and extreme memory-constrained environments (less common).                                               |
| **8-bit Integer**         | `torch.int8`      | 8-bit signed integer. Used for quantized models to save memory and computation in inference.                                                                                   |
| **16-bit Integer**        | `torch.int16`     | 16-bit signed integer. Useful for special numerical tasks requiring intermediate precision.                                                                                    |
| **32-bit Integer**        | `torch.int32`     | Standard signed integer type. Commonly used for indexing and general-purpose numerical tasks.                                                                                  |
| **64-bit Integer**        | `torch.int64`     | Long integer type. Often used for large indexing arrays or for tasks involving large numbers.                                                                                  |
| **8-bit Unsigned Integer**| `torch.uint8`     | 8-bit unsigned integer. Commonly used for image data (e.g., pixel values between 0 and 255).                                                                                    |
| **Boolean**               | `torch.bool`      | Boolean type, stores `True` or `False` values. Often used for masks in logical operations.                                                                                      |
| **Complex 64**            | `torch.complex64` | Complex number type with 32-bit real and 32-bit imaginary parts. Used for scientific and signal processing tasks.                                                               |
| **Complex 128**           | `torch.complex128`| Complex number type with 64-bit real and 64-bit imaginary parts. Offers higher precision but uses more memory.                                                                 |
| **Quantized Integer**     | `torch.qint8`     | Quantized signed 8-bit integer. Used in quantized models for efficient inference.                                                                                              |
| **Quantized Unsigned Integer** | `torch.quint8` | Quantized unsigned 8-bit integer. Often used for quantized tensors in image-related tasks.                                                                                     |


### 2.2) Tensor shape

In [14]:
a.shape

torch.Size([2, 3])

In [15]:
# _like(input) function creates a new tensor having the same shape, dtype, and device as the given tensor input. It’s a shortcut when you want a tensor with the same "forma"t
#  as another one.

torch.empty_like(a)

tensor([[-2.4444e-25,  4.3262e-41, -2.4444e-25],
        [ 4.3262e-41,  4.4842e-44,  0.0000e+00]])

In [16]:
torch.zeros_like(a)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [17]:
torch.ones_like(a)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [18]:
torch.rand_like(a)

tensor([[0.0830, 0.4253, 0.9149],
        [0.4799, 0.5348, 0.2695]])

### 2.3) Reshaping Tensors

In [19]:
a = torch.rand(4, 4)
a

tensor([[0.2530, 0.3390, 0.8367, 0.1289],
        [0.9693, 0.4495, 0.4031, 0.8202],
        [0.9792, 0.3278, 0.4076, 0.7276],
        [0.4506, 0.2334, 0.0411, 0.2441]])

In [20]:
# Reshape

b = a.reshape(2, 2, 2, 2)         # product of old shape dimensions = product of new shape dimensions; (4,4) = (2,2,2,2)
b

tensor([[[[0.2530, 0.3390],
          [0.8367, 0.1289]],

         [[0.9693, 0.4495],
          [0.4031, 0.8202]]],


        [[[0.9792, 0.3278],
          [0.4076, 0.7276]],

         [[0.4506, 0.2334],
          [0.0411, 0.2441]]]])

In [21]:
# Flatten

a.flatten()                 # Converts multi-dimension into 1D array

tensor([0.2530, 0.3390, 0.8367, 0.1289, 0.9693, 0.4495, 0.4031, 0.8202, 0.9792,
        0.3278, 0.4076, 0.7276, 0.4506, 0.2334, 0.0411, 0.2441])

In [22]:
# Permute: Reorders the dimensions (axes) of a tensor.

a = torch.randint(size = (2, 3, 4), low = 0, high = 10)
print(a.shape)

b = a.permute(2, 0, 1)             # returns a view of the tensor with the dimensions rearranged in the order you specify.
print(b.shape)


torch.Size([2, 3, 4])
torch.Size([4, 2, 3])


In [23]:
# Unsqueeze: Adds a dimension of size 1 at the specified position, useful to prepare tensors for broadcasting or batch processing.

a = torch.randint(size = (2, 3), low = 0, high = 10)
print(a.shape)

b = a.unsqueeze(0)                # Adds a dimesion at index 0
print(b.shape)

torch.Size([2, 3])
torch.Size([1, 2, 3])


In [24]:
# Squeeze: Removes dimensions of size 1 from a tensor, if a tensor does not have any dimension of size 1(ex: [2, 3, 4]), then .squeeze() will do nothing.

a = torch.randint(size = (1, 2, 1, 3), low = 0, high = 10)
print(a.shape)

b = a.squeeze()
print(b.shape)

torch.Size([1, 2, 1, 3])
torch.Size([2, 3])


# 3) Mathematical operations

### 3.1) Scalar operation

In [25]:
x = torch.rand(2, 2)
print(x)

tensor([[0.8501, 0.9642],
        [0.6270, 0.0568]])


In [26]:
# addition
print('Add: \n', x + 2)

# substraction
print('Subtract: \n', x - 2)

# multiplication
print('Multiply: \n', x * 3)

# division
print('Divde: \n', x / 3)

# int division/ floor division
res = (x * 100)//3
print('Floor division: \n', res)

# mod
mod = ((x * 100)//3)%2
print('Modulus: \n', mod)

# power
print('Power of 2: \n', x**2)

Add: 
 tensor([[2.8501, 2.9642],
        [2.6270, 2.0568]])
Subtract: 
 tensor([[-1.1499, -1.0358],
        [-1.3730, -1.9432]])
Multiply: 
 tensor([[2.5504, 2.8927],
        [1.8809, 0.1703]])
Divde: 
 tensor([[0.2834, 0.3214],
        [0.2090, 0.0189]])
Floor division: 
 tensor([[28., 32.],
        [20.,  1.]])
Modulus: 
 tensor([[0., 0.],
        [0., 1.]])
Power of 2: 
 tensor([[0.7228, 0.9298],
        [0.3931, 0.0032]])


### 3.2) Element wise operation

In [27]:
a = torch.rand(2,2)
b = torch.rand(2,2)
print(a)
print(b)

tensor([[0.0031, 0.2991],
        [0.2265, 0.5508]])
tensor([[0.3316, 0.1820],
        [0.0930, 0.6206]])


In [28]:
# addition
print('Add: \n', a + b)

# substraction
print('Subtract: \n', a - b)

# multiplication
print('Multiply: \n', a * b)

# division
print('Divde: \n', a / b)

# int division/ floor division
res = (a * 100)//b
print('Floor division: \n', res)

# mod
mod = (a * 100) % b
print('Modulus: \n', mod)

# power
print('Power: \n', a**b)

Add: 
 tensor([[0.3346, 0.4812],
        [0.3196, 1.1714]])
Subtract: 
 tensor([[-0.3285,  0.1171],
        [ 0.1335, -0.0699]])
Multiply: 
 tensor([[0.0010, 0.0545],
        [0.0211, 0.3418]])
Divde: 
 tensor([[0.0093, 1.6434],
        [2.4359, 0.8874]])
Floor division: 
 tensor([[  0., 164.],
        [243.,  88.]])
Modulus: 
 tensor([[0.3082, 0.0623],
        [0.0544, 0.4608]])
Power: 
 tensor([[0.1470, 0.8028],
        [0.8710, 0.6906]])


In [29]:
c = torch.tensor([[-1, 3, -5, 7]])
c

tensor([[-1,  3, -5,  7]])

In [30]:
# Absolute value of all elements

torch.abs(c)

tensor([[1, 3, 5, 7]])

In [31]:
# Negative of all elements

torch.neg(c)

tensor([[ 1, -3,  5, -7]])

In [32]:
# Rounding of all the elements

d = torch.tensor([0.6, 3.9, 9.1, 6.5])
print(d)

torch.round(d)

tensor([0.6000, 3.9000, 9.1000, 6.5000])


tensor([1., 4., 9., 6.])

In [33]:
# Taking Floor values(rounds down to the nearest integer) for all elements

torch.floor(d)

tensor([0., 3., 9., 6.])

In [34]:
# Taking the celing value(up to the nearest integer) for all elements

torch.ceil(d)

tensor([ 1.,  4., 10.,  7.])

In [35]:
# Clamping all elements; .clamp(input, min, max): restricts/clamps all elements of a tensor into a specified range[min, max]

torch.clamp(d, min = 3, max = 9)     # Any value less than min → set to min, & Any value greater than max → set to max.

tensor([3.0000, 3.9000, 9.0000, 6.5000])

### 3.3) Reduction operation
Whole matrix is reduced in a single number

In [36]:
x = torch.randint(size = (2, 3), low = 0, high = 10)
x

tensor([[6, 0, 5],
        [9, 6, 3]])

In [37]:
# Sum of entire matrix
print(torch.sum(x))

# Sum of all columns
print(torch.sum(x, dim = 0))

# Sum of all rows
print(torch.sum(x, dim = 1))

tensor(29)
tensor([15,  6,  8])
tensor([11, 18])


In [38]:
x = x.to(torch.float32)                       # For taking out mean data should be in float type

# Mean of entire matrix
print(torch.mean(x))

# Mean of all columns
print(torch.mean(x, dim = 0))

# Mean of all rows
print(torch.mean(x, dim = 1))

tensor(4.8333)
tensor([7.5000, 3.0000, 4.0000])
tensor([3.6667, 6.0000])


### PyTorch Statistical Functions and Dtype Behavior

| Function                              | Output Dtype (if input is int) | Notes                                                                 |
|---------------------------------------|--------------------------------|-----------------------------------------------------------------------|
| `torch.mean()`                        | Float (`float32` by default)   | Requires division → automatically promoted to float                   |
| `torch.std()` / `torch.var()`         | Float                          | Requires division & square root                                       |
| `torch.softmax()`                     | Float                          | Involves exponentials/division                                        |
| `torch.nn.functional.normalize()`     | Float                          | Division by norm → float needed                                       |
| **—**                                 | **—**                          | **—**                                                                 |
| `torch.median()`                      | Same as input (int allowed)    | Just selects middle element → no promotion needed                     |
| `torch.mode()`                        | Same as input (int allowed)    | Picks most frequent element                                           |
| `torch.min()` / `torch.max()`         | Same as input (int allowed)    | Returns existing values → no promotion                                |
| `torch.argmax()` / `torch.argmin()`   | Integer (indices)              | Returns index positions (always int, regardless of input dtype)       |


In [39]:
# Median
torch.median(x)

tensor(5.)

In [40]:
# Maximum element's value
print(torch.max(x))

# Minimum element's value
print(torch.min(x))

tensor(9.)
tensor(0.)


In [41]:
# Product of all elements
torch.prod(x)

tensor(0.)

In [42]:
# Standard deviation
torch.std(x)

tensor(3.0605)

In [43]:
# Varience
torch.var(x)

tensor(9.3667)

In [44]:
# argmax; tells location of leargest element
torch.argmax(x)

tensor(3)

In [45]:
# argmin; tells location of smallest element
torch.argmin(x)

tensor(1)

### 3.4) Matrix operation

In [46]:
a = torch.randint(size = (2, 2), low = 0, high = 10)
b = torch.randint(size = (2, 2), low = 0, high = 10)
print(a)
print(b)

tensor([[1, 3],
        [7, 5]])
tensor([[6, 5],
        [6, 9]])


In [47]:
# Matrix multiplication

torch.matmul(a, b)

tensor([[24, 32],
        [72, 80]])

In [48]:
vector1 = torch.tensor([1, 2])
vector2 = torch.tensor([3, 4])

# dot product
torch.dot(vector1, vector2)

tensor(11)

In [49]:
# Transpose of matrix

print(a)
torch.transpose(a, 0, 1)    # .transpose(input, dim0, dim1); It swaps two dimensions of a tensor, input → the tensor, dim0 → first dimension index,
                            # dim1 → second dimension index. a.T → works only for 2D tensors, same as torch.transpose(a, 0, 1) for higher-dimensional tensors,
                            # it swaps whichever two axes you pass in.

tensor([[1, 3],
        [7, 5]])


tensor([[1, 7],
        [3, 5]])

In [50]:
# Determinant of matrix

a = a.to(torch.float32)
torch.det(a)                                  # .det() needs floating values

tensor(-16.)

In [51]:
# Inverse of matrix

torch.inverse(a)

tensor([[-0.3125,  0.1875],
        [ 0.4375, -0.0625]])

### 3.5) Comparision operation

In [52]:
x = torch.randint(size = (2, 2), low = 0, high = 10)
y = torch.randint(size = (2, 2), low = 0, high = 10)
print(x)
print(y)

tensor([[4, 1],
        [2, 1]])
tensor([[7, 1],
        [5, 5]])


In [53]:
# Comparision operation returns boolean tensor, representing element-wise comparison results.

# greater than
print(x > y)

# less than
print(x < y)

# equal to
print(x == y)

# not equal to
print(x != y)

# greater than equal to
print(x >= y)

# less than equal to
print(x <= y)

tensor([[False, False],
        [False, False]])
tensor([[ True, False],
        [ True,  True]])
tensor([[False,  True],
        [False, False]])
tensor([[ True, False],
        [ True,  True]])
tensor([[False,  True],
        [False, False]])
tensor([[True, True],
        [True, True]])


### 3.6) Mathematical Functions

In [54]:
k = torch.randint(size = (2, 2), low = 0, high = 10)
print(k)

tensor([[3, 9],
        [9, 6]])


In [55]:
# Log function
torch.log(k)

tensor([[1.0986, 2.1972],
        [2.1972, 1.7918]])

In [56]:
# Exponent function
torch.exp(k)

tensor([[  20.0855, 8103.0840],
        [8103.0840,  403.4288]])

In [57]:
# Square root function
torch.sqrt(k)

tensor([[1.7321, 3.0000],
        [3.0000, 2.4495]])

In [58]:
# Sigmiog function
torch.sigmoid(k)

tensor([[0.9526, 0.9999],
        [0.9999, 0.9975]])

In [59]:
# Softmax function

k = k.to(torch.float64)
torch.softmax(k, dim = 0)                   # Softmax works on floating values

tensor([[0.0025, 0.9526],
        [0.9975, 0.0474]], dtype=torch.float64)

In [60]:
# Relu function

torch.relu(k)

tensor([[3., 9.],
        [9., 6.]], dtype=torch.float64)

# 4) Inplace Operation


- In PyTorch, an **in-place operation** directly modifies the contents of a tensor instead of creating a new one.
- They are marked with a **trailing underscore `_`**, ex: .add_(), .mul_(), etc

---

### 🔹 Why use In-place Operations?
- **Memory Efficient**:  
  In-place operations avoid creating new tensors, which saves memory.  
  For example, if you have a large dataset and perform an operation like addition, an out-of-place operation will allocate new memory for the result, but an in-place op will reuse the existing memory.  

- **Faster Execution**:  
  Since no extra memory allocation is needed, in-place ops can reduce overhead, especially on GPUs.

---

### ⚠️ Caution with Autograd
- In-place operations can **interfere with autograd** (PyTorch’s gradient tracking).  
- If you overwrite a tensor that is required later for backpropagation, PyTorch will raise an error:



In [61]:
m = torch.randint(size = (2, 2), low = 0, high = 10)
print(m)
n = torch.randint(size = (2, 2), low = 0, high = 10)
print(n)

tensor([[0, 5],
        [7, 4]])
tensor([[6, 9],
        [5, 9]])


In [62]:
# In-place-addition

m.add_(n)       # elements of m & n are added and then stored in m
print(m)

tensor([[ 6, 14],
        [12, 13]])


# 5) Coping Tensors


### ✅ `a = b`
- **Reference assignment** (shallow copy).
- `a` and `b` point to the **same underlying data**.
- No new memory is allocated.
- Changing one will also change the other.

---

### ✅ `a = b.clone()`
- **Deep copy** (new tensor).
- Creates a **completely independent tensor** with the same values as `b`.
- Memory is separate.
- Safe to modify `a` without affecting `b`.

---

### ✅ `a = b.detach()`
- **View (shallow copy)** that **shares data** with `b`.
- Detached from the **computation graph** (no gradient tracking).
- Useful when you want the values but don’t want autograd to track them.
- ⚠️ Changing data in `a` will also affect `b`.

---

### ✅ `a = b.detach().clone()`
- Best of both worlds:
  - Detaches from the computation graph.
  - Creates a **new independent copy** of the data.
- Safe option when you want both *no gradient tracking* and *separate memory*.

In [63]:
# Coping tensors through Reference assingement

a = torch.tensor([[1, 2, 3], [4, 5, 6]])

b = a                                 # Now b also points to tensor 'a'
print(a)
print(b)

a[0][0] = 9                           # Changes in a will automatically be seen through b
print(a)
print(b)

print('There memory location is same: ', id(a) == id(b))

tensor([[1, 2, 3],
        [4, 5, 6]])
tensor([[1, 2, 3],
        [4, 5, 6]])
tensor([[9, 2, 3],
        [4, 5, 6]])
tensor([[9, 2, 3],
        [4, 5, 6]])
There memory location is same:  True


In [64]:
# Cpoing tensor through deep copy

c = a.clone()
print(a)
print(c)

a[0][0] = 13             # Changes in a will not be seen in c
print(a)
print(c)

print('There memory location is same: ', id(a) == id(c))

tensor([[9, 2, 3],
        [4, 5, 6]])
tensor([[9, 2, 3],
        [4, 5, 6]])
tensor([[13,  2,  3],
        [ 4,  5,  6]])
tensor([[9, 2, 3],
        [4, 5, 6]])
There memory location is same:  False


# 6) Creating tensors on GPU

In [65]:
# By default, tensors are created on CPU

a = torch.randint(size = (2,3), low = 3, high = 10)
a.device

device(type='cpu')

In [66]:
# Creating a tensor on GPU

torch.cuda.is_available()

b = torch.rand((2, 3), device = 'cuda')
print(b.device)

cuda:0


In [67]:
# Moving existing tensor on GPU

c = a.to('cuda')                  # Now any operation performed on 'b' or 'c' will be performed on GPU
print(c.device)

cuda:0


# 7) Numpy and PyTorch

In [68]:
import numpy as np

a = np.array([1,2,3])
print(type(a))

<class 'numpy.ndarray'>


In [69]:
# Convert Numpy-array into tensor

b = torch.from_numpy(a)                       # Creates a tensor that shares memory with the NumPy array, changing one will change the other.
print(b.type)

c = torch.tensor(a)                           # Creates a copy of the NumPy array, changing one will not change the other.
c.type

<built-in method type of Tensor object at 0x78988ff78500>


<function Tensor.type>

In [70]:
# Convert tensor to numpy-array

x = torch.tensor([1, 2, 3])

y = x.numpy()                               # Works only for CPU tensors, returns a NumPy array sharing memory with the tensor.
print(type(y))

<class 'numpy.ndarray'>
